# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  tags:
    include:
    - v*
  branches:
    include:
    - main
    - feature/*
    - bugfix/*

resources:
  - repo: self

stages:

- stage: build
  dependsOn: []    # this removes the implicit dependency on previous stage and causes this to run in parallel
  jobs:
  - job:
    workspace:
      clean: all # what to clean up before the job runs
    pool: Custom
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'neoleukin-container-registry'
        repository: 'rosettafold'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: |
          $(Build.SourceBranchName)-$(Build.BuildId)
          $(Build.SourceBranchName)-$(Build.SourceVersion)
          $(Build.SourceBranchName)-latest
          $(Build.SourceBranchName) 